# Change these first
owner: 80px # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: 80px.com
    url: https://80px.com/health.txt
    expectedStatusCodes:
      - 200
assignees: # Users to assign downtime issues (optional)
  - markim
status-website: # Status website (optional)
  cname: uptime.80px.com # Custom domain CNAME
  # baseUrl: /repo
  # Uncomment the following line if you don't have a custom domain and add your repo name
  name: Uptime
  introTitle: "Status website for 80px."
  # introMessage: Thank you for stopping by.
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: 80px.com
      href: https://80px.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
