# Change these first
owner: 80px # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: 80px
    url: https://80px.com
  - name: urchinlyrics.com
    url: https://urchinlyrics.com
  - name: markmalone.us
    url: https://markmalone.us
  - name: texascherry.com
    url: https://texascherry.com
  - name: api.texascherry.com
    url: https://api.texascherry.com
  - name: lnwworldwide.org
    url: https://lnwworldwide.org

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: 80px.github.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://code.80px.com/uploads/-/system/appearance/logo/1/Semi-big_Logo.png
  name: 80px Uptime
  introTitle: "Status website for all 80px projects."
  introMessage: Thank you for stopping by.
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: 80px.com
      href: https://80px.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
